### ISSUE TITLE
suggesions

### ISSUE THREAD

**Issue by aelsharawi** [wpbullet/WP-Bullet-VPS-Installer#2]
Hi

Thanks for this cool installer

I'm using https://github.com/A5hleyRich/wordpress-nginx

could u please incorporate it into your Nginx for best of both worlds

also I'm compiling my own Nginx from here:

https://github.com/aelsharawi/nginx-ps-hdrs-cach

which was branched from Peters git.

====Also why not implement the free let's encrypt 

https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04

https://www.digitalocean.com/community/tutorials/how-to-secure-haproxy-with-let-s-encrypt-on-ubuntu-14-04

**Comment by wpbullet** [comment]
I am still tweaking my nginx configurations, I am sure you will see a lot of overlap between what I have and others.

Letsencrypt is planned for the future when I can reliably automate it (it is not easy for 6 different stacks as each has its own method). I use CloudFlare SSL which is much easier so Letsencrypt isn't a priority for me. You are welcome to contribute to a letsencrypt branch for it if you like and I'll happily accept the pull request.
