### ISSUE TITLE
create 2 lists

### ISSUE THREAD

**Issue by aelsharawi** [wpbullet/WP-Bullet-VPS-Installer#3]
first list :
chose one of the following:

1-nginx
2-apaceh
3-.......

===

and another list: that contains redis,.....

=====

also the swap files is not recommended on SSD vps, which most of the servers uses today

**Comment by wpbullet** [comment]
there is merit to the multiple lists, I don't see myself recoding that part of it though.

Where did your read that swap file isn't recommended?
