### ISSUE TITLE
add more tweaking for the server

### ISSUE THREAD

**Issue by aelsharawi** [wpbullet/WP-Bullet-VPS-Installer#7]
such as open tcp and http2 , brotli

==also

http://stackoverflow.com/questions/17015611/disable-tcp-slow-start

enable iw10

https://ckon.wordpress.com/2013/03/11/centos-6-4-supports-iw10-tcpip-tuning/

**Comment by wpbullet** [comment]
http2 will be available when nginx 1.10 is stable and not mainline so the dotdeb repo has it. I'm trying not to use too many different repos.

I didn't know about iw10, will look into it
